[[imagick]]
resize = [250, 250]
suffix = "-small"
format = ["webp", "jpg"]

[[imagick]]
resize = [500, 500]
format = "webp"

[[imagick]]
resize = [1000, 1000]
suffix = "-big"
format = "webp"

[[imagick]]
resize = [2000, 2000]
suffix = "-huge"
format = "webp"
